### PR TITLE
Fix player delete method to include params

### PR DESCRIPTION
**Pull request by javierjulio**
When working on #18 I made a mistake with the `params` usage and thought it wasn't needed. This argument is required to provide the `app_id` for a delete request which I missed on the documentation. Sorry about that!

### CODE REVIEW

**Review by tbalthazar — APPROVED** [review]
Thanks! :)

**Comment by tbalthazar** [comment]
Thanks @javierjulio.
Would you mind bumping the version and updating the changelog?
I'll publish a new version of the gem with the fix.
Thanks!

**Comment by tbalthazar** [comment]
@javierjulio I added a GH Action to automatically push to rubygems when PRs are merged to master.

**Comment by javierjulio** [comment]
@tbalthazar yes I will do that now, thanks!

**Comment by tbalthazar** [comment]
@javierjulio Thanks, 1.2.2 has been pushed to Rubygems :tada:

**Comment by javierjulio** [comment]
@tbalthazar thank you! ❤️

**Pull request merged**
